import type { Metadata } from "next";
import "./globals.css";
import { montserratAlternatesRegular } from "@/lib/utils/fonts";
import Header from "@/components/Layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserratAlternatesRegular.className}>
        
        
        <Header/>
        {children}
        
        
        </body>
    </html>
  );
}
