let {
  VITE_USERNAME_COLLECTION_ADDRESS,
  VITE_CARD_COLLECTION_ADDRESS,
  VITE_MARKETPLACE_ADDRESS,
  VITE_API_ENDPOINT,
  BASE_URL,
} = import.meta.env;

const USERNAME_COLLECTION_ADDRESS = VITE_USERNAME_COLLECTION_ADDRESS || "";
const CARD_COLLECTION_ADDRESS = VITE_CARD_COLLECTION_ADDRESS || "";
const MARKETPLACE_ADDRESS = VITE_MARKETPLACE_ADDRESS || "";
const API_ENDPOINT = VITE_API_ENDPOINT || "http://localhost:3000";

export default {
  USERNAME_COLLECTION_ADDRESS,
  CARD_COLLECTION_ADDRESS,
  MARKETPLACE_ADDRESS,
  API_ENDPOINT,
  BASE_URL,
};
