let { VITE_USERNAME_COLLECTION_ADDRESS, VITE_CARD_COLLECTION_ADDRESS } = import.meta.env;

const USERNAME_COLLECTION_ADDRESS = VITE_USERNAME_COLLECTION_ADDRESS || "";
const CARD_COLLECTION_ADDRESS = VITE_CARD_COLLECTION_ADDRESS || "";

export default { USERNAME_COLLECTION_ADDRESS, CARD_COLLECTION_ADDRESS };
