let { NEXT_PUBLIC_ENDPOINT, NEXT_PUBLIC_THIRDWEB_CLIENT_ID } = process.env;

const ENDPOINT_URL = NEXT_PUBLIC_ENDPOINT || "http://localhost:8085";
const THIRDWEB_CLIENT_ID = NEXT_PUBLIC_THIRDWEB_CLIENT_ID || "xxx";

export default { ENDPOINT_URL, THIRDWEB_CLIENT_ID };
